<div class="block filter">
    <div class="block-title filter-title">
        <strong><?php /* @escapeNotVerified */ echo __('Price') ?></strong>
    </div>
    <strong class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Price') ?></strong>
    <div class="js-price-slider">
        <span class="js-min"></span>
        <div class="js-bar"></div>
        <span class="js-max"></span>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".js-price-slider": {
            "priceSlider": {
                "min": 0,
                "max": 2000,
                "low": 200,
                "high": 1500
            }
        }
    }
</script>