<?php /** @var Space48\PriceSlider\Block\PriceSlider $block */ ?>
<div class="block price-slider">
    <div class="block-title slider-title">
        <strong><?php /* @escapeNotVerified */ echo __('Price') ?></strong>
    </div>
    <strong class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Price') ?></strong>
    <div class="js-price-slider">
        <div class="price-min">
            <span class="js-min"></span>
        </div>
        <div class="price-bar">
            <div class="js-bar"></div>
        </div>
        <div class="price-max">
            <span class="js-max"></span>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".js-price-slider": {
            "priceSlider": {
                "min": <?php echo $block->getProductsMinPrice() ?>,
                "max": <?php echo $block->getProductsMaxPrice() ?>,
                "low": <?php echo ($block->getSliderMinPrice()) ? $block->getSliderMinPrice() : 'null' ?>,
                "high": <?php echo ($block->getSliderMaxPrice()) ? $block->getSliderMaxPrice() : 'null' ?>,
                "waitTimeout": 2000,
                "currency": "£"
            }
        }
    }
</script>